name: instacard
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  stacked: ^3.4.0
  stacked_firebase_auth: ^2.20.0
  stacked_services: ^1.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  reactive_forms: ^17.0.1
  reactive_image_picker: ^5.0.1
  firebase_storage: ^11.7.7
  path_provider: ^2.1.3
  reactive_forms_generator: ^5.0.4
  reactive_forms_annotations: ^5.0.0
  freezed: 2.5.2
  freezed_annotation: ^2.4.1
  reactive_color_picker: ^2.0.1

  
dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  json_serializable: ^6.8.0
  isar_generator: ^3.1.0+1


dependency_overrides:
  analyzer: ^6.4.1
  

flutter:
  uses-material-design: true

